#line 2 "lex_sql.cpp"
/*
这里的代码会被复制到lex_sql.cpp的最开始位置
定义yy_size_t的原因是因为flex生成的代码，会使用yy_size_t与其他类型的数字
做比较，导致编译报警
*/
#define YY_TYPEDEF_YY_SIZE_T
typedef int yy_size_t;

#define YY_BUF_SIZE 80000

/* 参考生成的lex_sql.cpp代码，这个宏定义会放在每次运行yylex()最开始的地方 */
#define YY_USER_INIT                                         \
  yycolumn = 0;

/* 参考生成的lex_sql.cpp代码，这个宏定义会放在解析一个token之后，也可以在网上找到大量的参考资料 */
/* 我们在这里设置当前解析的token的位置信息，这样在yacc中就可以使用这些信息了 */
#define YY_USER_ACTION                                       \
do {                                                         \
  yylloc->first_line   = yylloc->last_line = yylineno;       \
  yylloc->first_column = yycolumn;                           \
  yylloc->last_column  = yylloc->first_column + yyleng - 1;  \
  yycolumn += yyleng;                                        \
}                                                            \
while (0);

bool check_date(int y, int m, int d);

#line 30 "lex_sql.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

#ifdef yyget_lloc
#define yyget_lloc_ALREADY_DEFINED
#else
#define yyget_lloc yyget_lloc
#endif

#ifdef yyset_lloc
#define yyset_lloc_ALREADY_DEFINED
#else
#define yyset_lloc yyset_lloc
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 83
#define YY_END_OF_BUFFER 84
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[272] =
    {   0,
        0,    0,    0,    0,   84,   82,    1,    2,   82,   82,
       82,   66,   67,   78,   76,   68,   77,    7,   79,    3,
        6,   73,   69,   75,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   83,   72,    0,   80,    0,
        0,    0,   81,    0,    0,    0,    3,   70,   71,   74,
       65,   65,   65,   34,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   37,
       36,   65,   65,   65,   65,   65,   65,   65,   65,   17,
       45,   65,   65,   65,   65,   65,   65,   65,   65,   65,

       65,   65,    0,    0,    0,    0,    4,   44,   43,   25,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   56,   65,   65,   65,   65,   22,   23,   46,   65,
       65,   65,   65,   65,   52,   65,   26,   65,   65,   65,
       65,   65,   65,   65,    0,    0,    0,    0,   65,   21,
       57,   65,   65,   65,   62,   59,   65,   10,   12,   65,
        8,   65,   65,   32,   65,   65,    9,   65,   65,   65,
       65,   48,   31,   65,   35,   61,   39,   65,   65,   65,
       65,   18,   19,   65,   60,   65,   65,   65,   65,    0,

        0,   53,   65,   24,   65,   65,   65,   65,   65,   58,
       65,   65,   16,   65,   30,   65,   65,   65,   65,   29,
       65,   13,   65,   65,   65,   33,    0,    0,    0,    0,
       54,   11,   65,   50,   38,   65,    0,   42,   63,   47,
       27,    0,   65,   20,   14,   15,   51,   49,    0,    0,
       65,   64,    0,    0,   65,    0,    0,    0,    0,   65,
       41,   40,   55,    5,    5,    5,    5,   65,   65,   28,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    1,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
        1,    1,    1,    1,   50,    1,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,   71,   72,   73,   74,
       75,   49,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    1,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2
    } ;

static const flex_int16_t yy_base[277] =
    {   0,
        0,    0,    0,    0,  150, 2193, 2193, 2193,  125,   71,
       76, 2193, 2193, 2193, 2193, 2193, 2193, 2193, 2193,   83,
     2193,   55, 2193,  123,   88,   93,  146,   91,  119,  157,
      164,  184,  205,  211,  235,  240,  247,  265,  270,  275,
      326,  300,  343,  348,  360, 2193, 2193,  138, 2193,  387,
      395,  134, 2193,  331,  409,  370,  404, 2193, 2193, 2193,
        0,  414,  419,  424,  436,  441,  446,  467,  484,  494,
      508,  515,  520,  527,  545,  552,  557,  581,  586,  639,
      596,  612,  622,  617,  645,  672,  683,  695,  706,  711,
      716,  734,  739,  745,  770,  775,  798,  809,  803,  825,

      830,  842,  858,  883,  888,  902,  894,  907,  912,  917,
      922,  927,  932,  940,  945,  950,  968,  989,  995, 1010,
     1015, 1020, 1035, 1045, 1050, 1055, 1073, 1081, 1086, 1107,
     1112, 1131, 1136, 1141, 1159, 1164, 1186, 1191, 1204, 1209,
     1214, 1219, 1230, 1240, 1245, 1257, 1267, 1272, 1289, 1294,
     1299, 1304, 1316, 1326,  108, 1353,   73, 1367, 1359, 1331,
     1373, 1382, 1387, 1392, 1400, 1409, 1421, 1427, 1432, 1437,
     1450, 1455, 1466, 1471, 1477, 1482, 1495, 1505, 1510, 1515,
     1522, 1532, 1542, 1549, 1558, 1569, 1578, 1583, 1588, 1593,
     1599, 1611, 1616, 1626, 1640, 1645, 1650, 1655, 1660, 1679,

     1684, 1689, 1706, 1711, 1716, 1721, 1736, 1741, 1750, 1769,
     1777, 1782, 1787, 1798, 1803, 1812, 1817, 1841, 1846, 1861,
     1868, 1873, 1884, 1889, 1903, 1908, 1931,  111, 1945,  112,
     1913, 1937, 1950, 1958, 1963, 1968,   89, 1974, 1979, 1984,
     1991,   92, 2001, 2006, 2018, 2023, 2028, 2033, 2048, 2053,
     2058, 2063,   78,   79, 2068, 2088,   75, 2095,   78, 2073,
     2193, 2193, 2100, 2193,  134,  125, 2193, 2106, 2116, 2122,
     2193, 2186, 2188, 2190,  126,   95
    } ;

static const flex_int16_t yy_def[277] =
    {   0,
      271,    1,  272,  272,  271,  271,  271,  271,  271,  273,
      274,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  275,  275,  275,   27,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  271,  271,  273,  271,  273,
      273,  274,  271,  274,  274,  271,  271,  271,  271,  271,
      276,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,

      275,  275,  273,  273,  274,  274,  271,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  273,  273,  274,  274,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  273,

      274,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  273,  273,  274,  274,
      275,  275,  275,  275,  275,  275,  271,  275,  275,  275,
      275,  271,  275,  275,  275,  275,  275,  275,  273,  274,
      275,  275,  271,  271,  275,  273,  273,  274,  274,  275,
      271,  271,  275,  271,  273,  274,  271,  275,  275,  275,
        0,  271,  271,  271,  271,  271
    } ;

static const flex_int16_t yy_nxt[2269] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   20,   20,   20,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   35,   35,
       40,   41,   42,   43,   44,   45,   35,   35,   35,   35,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   35,   35,   40,   41,   42,
       43,   44,   45,   35,   35,   49,   58,   59,   53,  264,
      265,   53,  266,  267,  201,   50,   51,   51,   50,   50,
       54,   55,   55,   54,   54,   56,   61,   57,   57,   57,

       57,   57,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   49,  253,   71,   49,  254,   53,   72,  200,
       66,   62,  249,  250,   63,  261,  262,   62,   62,   64,
       53,   73,   65,   61,   61,   61,   61,   61,   49,   53,
      253,   71,   49,  254,   60,   72,   47,   66,   62,  271,
      271,   63,  261,  262,  271,   62,   64,  271,   73,   65,
       61,   61,   61,   61,   61,   74,  271,  271,  271,   67,
      271,   61,   61,   61,   61,   61,   68,  271,   61,   61,
       61,   61,   61,   69,  271,  271,   70,  271,  271,  271,
      271,   75,   74,  271,  271,  271,   67,   76,   61,   61,

       61,   61,   61,   68,   77,  271,  271,   78,  271,  271,
       69,   79,  271,   70,  271,  271,  271,  271,   75,   61,
       61,   61,   61,   61,   76,   61,   61,   61,   61,   61,
      271,   77,  271,  271,   78,  271,  271,  271,   79,  271,
      271,   80,  271,  271,  271,  271,   81,  271,   82,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,  271,
      271,   61,   61,   61,   61,   61,  271,   83,   80,  271,
       86,   84,  271,   81,  271,   82,  271,   85,   87,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   83,  271,  271,   86,   84,  271,

      271,  271,   88,  271,   85,   87,   90,  271,   89,  271,
       91,  271,   92,  271,   61,   61,   61,   61,   61,  271,
      271,  271,  271,   97,  271,  271,  271,   98,  271,   88,
      271,  271,  271,   90,  271,   89,   53,   91,  271,   92,
       61,   61,   61,   61,   61,  105,  105,  105,  105,  105,
       97,  271,  271,   93,   98,  271,   94,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,  271,  271,   95,
      271,  101,  271,   96,   61,   61,   61,   61,   61,   99,
       93,  100,  271,   94,  107,  107,  107,  107,  107,  271,
      102,   49,  271,  271,  271,  271,   95,  271,  101,   49,

       96,  103,  103,  103,  103,  103,   99,  271,  100,  104,
      104,  104,  104,  104,   53,  271,   56,  102,   57,   57,
       57,   57,   57,  106,  106,  106,  106,  106,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,  271,  271,  108,  271,  271,  271,  109,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,  110,  271,  271,  271,  271,
      111,  271,  108,  271,  271,  271,  109,  271,  271,  271,
      112,   61,   61,   61,   61,   61,  271,  271,  271,  271,
      113,  271,  110,  271,  271,  271,  271,  111,   61,   61,

       61,   61,   61,  271,  271,  271,  271,  112,   61,   61,
       61,   61,   61,  271,  271,  271,  271,  113,  271,  114,
      271,  116,   61,   61,   61,   61,   61,  115,  271,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,  271,
      271,   61,   61,   61,   61,   61,  114,  271,  116,  118,
      117,  271,  271,  271,  115,  271,  119,  120,  121,   61,
       61,   61,   61,   61,  271,  122,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,  118,  117,  271,  271,
      271,  271,  123,  119,  120,  121,  271,  271,  271,  124,
      271,  271,  122,  271,  125,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   61,  271,  271,  271,  271,  123,
       61,   61,   61,   61,   61,  271,  124,  271,  271,  271,
      127,  125,  271,  271,  271,  126,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,  271,  271,  133,  271,  271,  271,  127,  271,  271,
      135,  271,  126,   61,   61,   61,   61,   61,  134,   61,
       61,   61,   61,   61,  271,  128,  271,  129,  136,  271,
      133,  271,  271,  271,  271,  130,  271,  135,  271,  271,
      131,  132,  271,  271,  271,  134,   61,   61,   61,   61,
       61,  271,  128,  271,  129,  136,  271,   61,   61,   61,

       61,   61,  130,  271,  271,  271,  271,  131,  132,   61,
       61,   61,   61,   61,  271,  271,  271,  271,  137,  138,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,  271,  271,  139,  271,  271,
      140,  271,  141,  271,  271,  137,  138,  271,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,  271,   61,
       61,   61,   61,   61,  139,  271,  271,  140,  142,  141,
      271,  271,  271,  144,  271,  271,  271,  143,  271,  271,
      271,  145,  146,  271,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,  271,  142,  271,  271,  271,  271,

      144,  271,  271,  271,  143,  147,  271,  271,  145,  146,
      271,  148,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,  149,   61,   61,   61,   61,   61,  271,  271,
      271,  271,  147,  271,  151,  271,  271,  271,  148,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,  149,
      271,  152,  271,  271,  271,  150,   61,   61,   61,   61,
       61,  151,   49,  271,  153,  271,  271,  271,  271,  154,
      271,  271,  155,  155,  155,  155,  155,  271,  152,  271,
      271,  271,  150,  271,  271,  271,  271,   49,  271,  271,
      271,  153,  271,   53,  271,  271,  154,  156,  156,  156,

      156,  156,  157,  157,  157,  157,  157,   53,  107,  107,
      107,  107,  107,  271,  271,  271,  158,  158,  158,  158,
      158,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,  271,  160,  159,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,  271,
      271,  271,  161,  164,  271,  162,  271,  271,  271,  160,
      159,  163,   61,   61,   61,   61,   61,  271,  271,  271,
      271,  165,  271,  271,  271,  166,  271,  271,  271,  161,

      164,  271,  162,   61,   61,   61,   61,   61,  163,   61,
       61,   61,   61,   61,  271,  271,  167,  271,  165,  271,
      168,  271,  166,  271,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,  271,
      271,  271,  271,  167,  271,  271,  271,  168,  169,   61,
       61,   61,   61,   61,  172,  271,  170,  171,  173,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,  271,  169,  271,  271,  271,  271,
      174,  172,  271,  170,  171,  173,  176,   61,   61,   61,
       61,   61,  271,  175,  271,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   61,  271,  271,  174,  178,  271,
      271,  177,  271,  176,  271,  271,  271,  179,  271,  271,
      175,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,  271,  271,  271,  180,  178,  271,  271,  177,  181,
      271,  271,  271,  271,  179,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
      271,  180,  271,  271,  271,  271,  181,  271,  182,  271,
      184,  271,  183,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,  271,  271,  271,  185,  271,  271,  271,
      186,  271,  271,  271,  271,  182,  271,  184,  271,  183,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
      271,  271,  271,  185,  271,  271,  271,  186,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,  271,  271,
      271,  188,  271,  187,   61,   61,   61,   61,   61,  271,
      271,  271,  271,  189,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,  271,  271,  190,  191,  188,  271,
      187,   61,   61,   61,   61,   61,  271,  271,  271,  271,
      189,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,  271,  271,  190,  191,  271,  271,  193,  271,  271,

      271,  271,  192,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,  194,  193,  271,  271,  197,  271,  192,
       61,   61,   61,   61,   61,  271,  195,  271,  196,  271,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
      194,  271,  271,  271,  197,  271,  271,   49,  271,  198,
      271,  271,  271,  195,  200,  196,  199,  155,  155,  155,
      155,  155,   53,   61,   61,   61,   61,   61,  201,  271,
      271,  157,  157,  157,  157,  157,  198,   61,   61,   61,
       61,   61,  271,  199,  271,  202,   61,   61,   61,   61,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,  271,  271,  203,   61,   61,   61,   61,   61,  271,
      271,  271,  202,   61,   61,   61,   61,   61,  271,  204,
      271,  271,  271,  271,  205,   61,   61,   61,   61,   61,
      203,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,  204,  271,  206,  271,
      271,  205,  271,  207,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,  271,  271,  271,  271,  209,  208,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
      207,   61,   61,   61,   61,   61,   61,   61,   61,   61,

       61,  271,  271,  271,  271,  209,  208,  271,  210,   61,
       61,   61,   61,   61,  271,  211,  271,  271,  212,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,  271,  210,   61,   61,   61,   61,
       61,  271,  211,  271,  214,  212,   61,   61,   61,   61,
       61,  213,  271,  271,  271,  215,   61,   61,   61,   61,
       61,  271,  216,   61,   61,   61,   61,   61,  271,  271,
      271,  214,   61,   61,   61,   61,   61,  271,  213,  271,
      271,  271,  215,   61,   61,   61,   61,   61,  271,  216,
      271,  217,   61,   61,   61,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,  219,   61,   61,   61,   61,   61,  217,  220,
      271,  271,  271,  218,  221,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,  271,  271,  271,  271,  219,
       61,   61,   61,   61,   61,  271,  220,  271,  271,  271,
      218,  221,  271,  222,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,  271,
      222,  271,  225,   49,  271,  271,  271,  226,  223,   53,
      271,  271,  224,  227,  227,  228,  228,  228,  229,  229,

      230,  230,  230,   61,   61,   61,   61,   61,  271,  225,
      271,  271,  271,  271,  226,  223,  271,  271,  271,  224,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
      271,  271,  271,  232,  271,  271,  271,  271,  231,  233,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
      271,  271,  271,  234,   61,   61,   61,   61,   61,  271,
      232,  271,  271,  271,  271,  231,  233,  271,  237,  271,
      271,  236,  235,   61,   61,   61,   61,   61,  271,  271,
      234,   61,   61,   61,   61,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   61,   61,  271,  271,  236,  235,
      271,  238,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,  271,  271,  271,  239,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,  271,  271,  238,  271,
      271,  271,  242,  271,  271,  271,  271,  241,  271,  271,
      271,  271,  239,  271,  240,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,  271,  271,  271,  271,  243,
      271,  271,  271,  271,  241,   61,   61,   61,   61,   61,
      271,  240,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,  271,  271,  271,  271,  243,  271,   61,   61,

       61,   61,   61,   61,   61,   61,   61,   61,  271,  271,
      244,  246,  271,  271,  245,  271,  247,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,  271,  271,  271,   49,  271,  244,  246,  271,
      271,  245,  249,  247,  248,  228,  228,  228,  228,  228,
       53,   61,   61,   61,   61,   61,  250,  271,  271,  230,
      230,  230,  230,  230,   61,   61,   61,   61,   61,  271,
      271,  248,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,  251,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,

       61,   61,   61,  271,  252,   61,   61,   61,   61,   61,
      271,  271,  271,  271,  251,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,  271,  255,  271,  271,  271,
      271,  252,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   49,  255,  271,  271,  271,  271,   53,  271,
      271,  271,  256,  256,  256,  256,  257,  258,  258,  258,
      258,  259,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,  264,  265,  271,  271,  271,  271,  260,  266,

      267,  263,  257,  257,  257,  257,  257,  271,  268,  259,
      259,  259,  259,  259,   61,   61,   61,   61,   61,  271,
       61,   61,   61,   61,   61,  260,  271,  271,  263,  269,
       61,   61,   61,   61,   61,  268,   61,   61,   61,   61,
       61,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  269,  271,  270,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  270,   46,   46,   48,   48,
       52,   52,    5,  271,  271,  271,  271,  271,  271,  271,

      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271
    } ;

static const flex_int16_t yy_chk[2269] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   10,   22,   22,  157,  257,
      257,   11,  259,  259,  157,   10,   10,   10,   10,   10,
       11,   11,   11,   11,   11,   20,  276,   20,   20,   20,

       20,   20,   25,   25,   25,   25,   25,   26,   26,   26,
       26,   26,  155,  237,   28,  228,  242,  230,   28,  155,
       26,   28,  228,  230,   25,  253,  254,  275,   28,   25,
      266,   28,   25,   29,   29,   29,   29,   29,  265,   52,
      237,   28,   48,  242,   24,   28,    9,   26,   28,    5,
        0,   25,  253,  254,    0,   28,   25,    0,   28,   25,
       27,   27,   27,   27,   27,   29,    0,    0,    0,   27,
        0,   30,   30,   30,   30,   30,   27,    0,   31,   31,
       31,   31,   31,   27,    0,    0,   27,    0,    0,    0,
        0,   30,   29,    0,    0,    0,   27,   30,   32,   32,

       32,   32,   32,   27,   31,    0,    0,   32,    0,    0,
       27,   32,    0,   27,    0,    0,    0,    0,   30,   33,
       33,   33,   33,   33,   30,   34,   34,   34,   34,   34,
        0,   31,    0,    0,   32,    0,    0,    0,   32,    0,
        0,   33,    0,    0,    0,    0,   33,    0,   34,   35,
       35,   35,   35,   35,   36,   36,   36,   36,   36,    0,
        0,   37,   37,   37,   37,   37,    0,   36,   33,    0,
       37,   36,    0,   33,    0,   34,    0,   36,   37,   38,
       38,   38,   38,   38,   39,   39,   39,   39,   39,   40,
       40,   40,   40,   40,   36,    0,    0,   37,   36,    0,

        0,    0,   38,    0,   36,   37,   39,    0,   38,    0,
       39,    0,   40,    0,   42,   42,   42,   42,   42,    0,
        0,    0,    0,   42,    0,    0,    0,   42,    0,   38,
        0,    0,    0,   39,    0,   38,   54,   39,    0,   40,
       41,   41,   41,   41,   41,   54,   54,   54,   54,   54,
       42,    0,    0,   41,   42,    0,   41,   43,   43,   43,
       43,   43,   44,   44,   44,   44,   44,    0,    0,   41,
        0,   44,    0,   41,   45,   45,   45,   45,   45,   43,
       41,   43,    0,   41,   56,   56,   56,   56,   56,    0,
       45,   50,    0,    0,    0,    0,   41,    0,   44,   51,

       41,   50,   50,   50,   50,   50,   43,    0,   43,   51,
       51,   51,   51,   51,   55,    0,   57,   45,   57,   57,
       57,   57,   57,   55,   55,   55,   55,   55,   62,   62,
       62,   62,   62,   63,   63,   63,   63,   63,   64,   64,
       64,   64,   64,    0,    0,   63,    0,    0,    0,   64,
       65,   65,   65,   65,   65,   66,   66,   66,   66,   66,
       67,   67,   67,   67,   67,   65,    0,    0,    0,    0,
       66,    0,   63,    0,    0,    0,   64,    0,    0,    0,
       67,   68,   68,   68,   68,   68,    0,    0,    0,    0,
       68,    0,   65,    0,    0,    0,    0,   66,   69,   69,

       69,   69,   69,    0,    0,    0,    0,   67,   70,   70,
       70,   70,   70,    0,    0,    0,    0,   68,    0,   69,
        0,   70,   71,   71,   71,   71,   71,   69,    0,   72,
       72,   72,   72,   72,   73,   73,   73,   73,   73,    0,
        0,   74,   74,   74,   74,   74,   69,    0,   70,   72,
       71,    0,    0,    0,   69,    0,   72,   73,   74,   75,
       75,   75,   75,   75,    0,   74,   76,   76,   76,   76,
       76,   77,   77,   77,   77,   77,   72,   71,    0,    0,
        0,    0,   75,   72,   73,   74,    0,    0,    0,   76,
        0,    0,   74,    0,   77,   78,   78,   78,   78,   78,

       79,   79,   79,   79,   79,    0,    0,    0,    0,   75,
       81,   81,   81,   81,   81,    0,   76,    0,    0,    0,
       79,   77,    0,    0,    0,   78,   82,   82,   82,   82,
       82,   84,   84,   84,   84,   84,   83,   83,   83,   83,
       83,    0,    0,   82,    0,    0,    0,   79,    0,    0,
       84,    0,   78,   80,   80,   80,   80,   80,   83,   85,
       85,   85,   85,   85,    0,   80,    0,   80,   85,    0,
       82,    0,    0,    0,    0,   80,    0,   84,    0,    0,
       80,   80,    0,    0,    0,   83,   86,   86,   86,   86,
       86,    0,   80,    0,   80,   85,    0,   87,   87,   87,

       87,   87,   80,    0,    0,    0,    0,   80,   80,   88,
       88,   88,   88,   88,    0,    0,    0,    0,   86,   87,
       89,   89,   89,   89,   89,   90,   90,   90,   90,   90,
       91,   91,   91,   91,   91,    0,    0,   88,    0,    0,
       89,    0,   91,    0,    0,   86,   87,    0,   92,   92,
       92,   92,   92,   93,   93,   93,   93,   93,    0,   94,
       94,   94,   94,   94,   88,    0,    0,   89,   92,   91,
        0,    0,    0,   93,    0,    0,    0,   92,    0,    0,
        0,   93,   94,    0,   95,   95,   95,   95,   95,   96,
       96,   96,   96,   96,    0,   92,    0,    0,    0,    0,

       93,    0,    0,    0,   92,   95,    0,    0,   93,   94,
        0,   96,   97,   97,   97,   97,   97,   99,   99,   99,
       99,   99,   97,   98,   98,   98,   98,   98,    0,    0,
        0,    0,   95,    0,   99,    0,    0,    0,   96,  100,
      100,  100,  100,  100,  101,  101,  101,  101,  101,   97,
        0,  100,    0,    0,    0,   98,  102,  102,  102,  102,
      102,   99,  103,    0,  101,    0,    0,    0,    0,  102,
        0,    0,  103,  103,  103,  103,  103,    0,  100,    0,
        0,    0,   98,    0,    0,    0,    0,  104,    0,    0,
        0,  101,    0,  105,    0,    0,  102,  104,  104,  104,

      104,  104,  105,  105,  105,  105,  105,  106,  107,  107,
      107,  107,  107,    0,    0,    0,  106,  106,  106,  106,
      106,  108,  108,  108,  108,  108,  109,  109,  109,  109,
      109,  110,  110,  110,  110,  110,  111,  111,  111,  111,
      111,  112,  112,  112,  112,  112,  113,  113,  113,  113,
      113,    0,  112,  111,  114,  114,  114,  114,  114,  115,
      115,  115,  115,  115,  116,  116,  116,  116,  116,    0,
        0,    0,  113,  116,    0,  114,    0,    0,    0,  112,
      111,  115,  117,  117,  117,  117,  117,    0,    0,    0,
        0,  117,    0,    0,    0,  117,    0,    0,    0,  113,

      116,    0,  114,  118,  118,  118,  118,  118,  115,  119,
      119,  119,  119,  119,    0,    0,  118,    0,  117,    0,
      119,    0,  117,    0,  120,  120,  120,  120,  120,  121,
      121,  121,  121,  121,  122,  122,  122,  122,  122,    0,
        0,    0,    0,  118,    0,    0,    0,  119,  120,  123,
      123,  123,  123,  123,  122,    0,  121,  121,  123,  124,
      124,  124,  124,  124,  125,  125,  125,  125,  125,  126,
      126,  126,  126,  126,    0,  120,    0,    0,    0,    0,
      124,  122,    0,  121,  121,  123,  126,  127,  127,  127,
      127,  127,    0,  125,    0,  128,  128,  128,  128,  128,

      129,  129,  129,  129,  129,    0,    0,  124,  128,    0,
        0,  127,    0,  126,    0,    0,    0,  129,    0,    0,
      125,  130,  130,  130,  130,  130,  131,  131,  131,  131,
      131,    0,    0,    0,  130,  128,    0,    0,  127,  131,
        0,    0,    0,    0,  129,  132,  132,  132,  132,  132,
      133,  133,  133,  133,  133,  134,  134,  134,  134,  134,
        0,  130,    0,    0,    0,    0,  131,    0,  132,    0,
      134,    0,  133,  135,  135,  135,  135,  135,  136,  136,
      136,  136,  136,    0,    0,    0,  135,    0,    0,    0,
      136,    0,    0,    0,    0,  132,    0,  134,    0,  133,

      137,  137,  137,  137,  137,  138,  138,  138,  138,  138,
        0,    0,    0,  135,    0,    0,    0,  136,  139,  139,
      139,  139,  139,  140,  140,  140,  140,  140,  141,  141,
      141,  141,  141,  142,  142,  142,  142,  142,    0,    0,
        0,  141,    0,  140,  143,  143,  143,  143,  143,    0,
        0,    0,    0,  142,  144,  144,  144,  144,  144,  145,
      145,  145,  145,  145,    0,    0,  143,  144,  141,    0,
      140,  146,  146,  146,  146,  146,    0,    0,    0,    0,
      142,  147,  147,  147,  147,  147,  148,  148,  148,  148,
      148,    0,    0,  143,  144,    0,    0,  148,    0,    0,

        0,    0,  146,  149,  149,  149,  149,  149,  150,  150,
      150,  150,  150,  151,  151,  151,  151,  151,  152,  152,
      152,  152,  152,  149,  148,    0,    0,  152,    0,  146,
      153,  153,  153,  153,  153,    0,  150,    0,  151,    0,
      154,  154,  154,  154,  154,  160,  160,  160,  160,  160,
      149,    0,    0,    0,  152,    0,    0,  156,    0,  153,
        0,    0,    0,  150,  156,  151,  154,  156,  156,  156,
      156,  156,  158,  159,  159,  159,  159,  159,  158,    0,
        0,  158,  158,  158,  158,  158,  153,  161,  161,  161,
      161,  161,    0,  154,    0,  159,  162,  162,  162,  162,

      162,  163,  163,  163,  163,  163,  164,  164,  164,  164,
      164,    0,    0,  162,  165,  165,  165,  165,  165,    0,
        0,    0,  159,  166,  166,  166,  166,  166,    0,  163,
        0,    0,    0,    0,  164,  167,  167,  167,  167,  167,
      162,  168,  168,  168,  168,  168,  169,  169,  169,  169,
      169,  170,  170,  170,  170,  170,  163,    0,  166,    0,
        0,  164,    0,  167,  171,  171,  171,  171,  171,  172,
      172,  172,  172,  172,    0,    0,    0,    0,  172,  170,
      173,  173,  173,  173,  173,  174,  174,  174,  174,  174,
      167,  175,  175,  175,  175,  175,  176,  176,  176,  176,

      176,    0,    0,    0,    0,  172,  170,    0,  173,  177,
      177,  177,  177,  177,    0,  175,    0,    0,  176,  178,
      178,  178,  178,  178,  179,  179,  179,  179,  179,  180,
      180,  180,  180,  180,    0,  173,  181,  181,  181,  181,
      181,    0,  175,    0,  179,  176,  182,  182,  182,  182,
      182,  178,    0,    0,    0,  180,  183,  183,  183,  183,
      183,    0,  181,  184,  184,  184,  184,  184,    0,    0,
        0,  179,  185,  185,  185,  185,  185,    0,  178,    0,
        0,    0,  180,  186,  186,  186,  186,  186,    0,  181,
        0,  184,  187,  187,  187,  187,  187,  188,  188,  188,

      188,  188,  189,  189,  189,  189,  189,  190,  190,  190,
      190,  190,  189,  191,  191,  191,  191,  191,  184,  190,
        0,    0,    0,  188,  191,  192,  192,  192,  192,  192,
      193,  193,  193,  193,  193,    0,    0,    0,    0,  189,
      194,  194,  194,  194,  194,    0,  190,    0,    0,    0,
      188,  191,    0,  194,  195,  195,  195,  195,  195,  196,
      196,  196,  196,  196,  197,  197,  197,  197,  197,  198,
      198,  198,  198,  198,  199,  199,  199,  199,  199,    0,
      194,    0,  198,  200,    0,    0,    0,  199,  196,  201,
        0,    0,  197,  200,  200,  200,  200,  200,  201,  201,

      201,  201,  201,  202,  202,  202,  202,  202,    0,  198,
        0,    0,    0,    0,  199,  196,    0,    0,    0,  197,
      203,  203,  203,  203,  203,  204,  204,  204,  204,  204,
      205,  205,  205,  205,  205,  206,  206,  206,  206,  206,
        0,    0,    0,  205,    0,    0,    0,    0,  203,  206,
      207,  207,  207,  207,  207,  208,  208,  208,  208,  208,
        0,    0,    0,  207,  209,  209,  209,  209,  209,    0,
      205,    0,    0,    0,    0,  203,  206,    0,  211,    0,
        0,  209,  208,  210,  210,  210,  210,  210,    0,    0,
      207,  211,  211,  211,  211,  211,  212,  212,  212,  212,

      212,  213,  213,  213,  213,  213,    0,    0,  209,  208,
        0,  212,  214,  214,  214,  214,  214,  215,  215,  215,
      215,  215,    0,    0,    0,  214,  216,  216,  216,  216,
      216,  217,  217,  217,  217,  217,    0,    0,  212,    0,
        0,    0,  218,    0,    0,    0,    0,  217,    0,    0,
        0,    0,  214,    0,  216,  218,  218,  218,  218,  218,
      219,  219,  219,  219,  219,    0,    0,    0,    0,  219,
        0,    0,    0,    0,  217,  220,  220,  220,  220,  220,
        0,  216,  221,  221,  221,  221,  221,  222,  222,  222,
      222,  222,    0,    0,    0,    0,  219,    0,  223,  223,

      223,  223,  223,  224,  224,  224,  224,  224,    0,    0,
      221,  223,    0,    0,  222,    0,  224,  225,  225,  225,
      225,  225,  226,  226,  226,  226,  226,  231,  231,  231,
      231,  231,    0,    0,    0,  227,    0,  221,  223,    0,
        0,  222,  227,  224,  225,  227,  227,  227,  227,  227,
      229,  232,  232,  232,  232,  232,  229,    0,    0,  229,
      229,  229,  229,  229,  233,  233,  233,  233,  233,    0,
        0,  225,  234,  234,  234,  234,  234,  235,  235,  235,
      235,  235,  236,  236,  236,  236,  236,  233,  238,  238,
      238,  238,  238,  239,  239,  239,  239,  239,  240,  240,

      240,  240,  240,    0,  236,  241,  241,  241,  241,  241,
        0,    0,    0,    0,  233,  243,  243,  243,  243,  243,
      244,  244,  244,  244,  244,    0,  243,    0,    0,    0,
        0,  236,  245,  245,  245,  245,  245,  246,  246,  246,
      246,  246,  247,  247,  247,  247,  247,  248,  248,  248,
      248,  248,  249,  243,    0,    0,    0,    0,  250,    0,
        0,    0,  249,  249,  249,  249,  249,  250,  250,  250,
      250,  250,  251,  251,  251,  251,  251,  252,  252,  252,
      252,  252,  255,  255,  255,  255,  255,  260,  260,  260,
      260,  260,  256,  256,    0,    0,    0,    0,  251,  258,

      258,  255,  256,  256,  256,  256,  256,    0,  260,  258,
      258,  258,  258,  258,  263,  263,  263,  263,  263,    0,
      268,  268,  268,  268,  268,  251,    0,    0,  255,  268,
      269,  269,  269,  269,  269,  260,  270,  270,  270,  270,
      270,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  268,    0,  269,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  269,  272,  272,  273,  273,
      274,  274,  271,  271,  271,  271,  271,  271,  271,  271,

      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lex_sql.l"

#line 31 "lex_sql.l"
#include<string.h>
#include<stdio.h>

/**
 * flex 代码包含三个部分，使用 %% 分隔
 * 第一个部分的代码是C代码，flex会原样复制到目标文件中
 * 第二个部分是规则部分，使用正则表达式定义一系列规则
 * 第三个部分还是C代码，flex 会复制此段代码
 */

#include "sql/parser/parse_defs.h"
#include "common/log/log.h"
#include "yacc_sql.hpp"

#ifndef register
#define register 
#endif // register

extern int atoi();
extern double atof();

#define RETURN_TOKEN(token) LOG_DEBUG("%s", #token);return token
#line 1086 "lex_sql.cpp"
/* Prevent the need for linking with -lfl */
#define YY_NO_INPUT 1
/* 不区分大小写 */

/* 规则匹配的优先级：*/
/* 1. 匹配的规则长的优先 */
/* 2. 写在最前面的优先 */
/* yylval 就可以认为是 yacc 中 %union 定义的结构体(union 结构) */
#line 1095 "lex_sql.cpp"

#define INITIAL 0
#define STR 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

       YYLTYPE *yyget_lloc ( yyscan_t yyscanner );
    
        void yyset_lloc ( YYLTYPE * yylloc_param , yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 78 "lex_sql.l"


#line 1381 "lex_sql.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 272 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2193 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 80 "lex_sql.l"
// ignore whitespace
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 81 "lex_sql.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 83 "lex_sql.l"
yylval->number=atoi(yytext); RETURN_TOKEN(NUMBER);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 84 "lex_sql.l"
yylval->floats=(float)(atof(yytext)); RETURN_TOKEN(FLOAT);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 85 "lex_sql.l"
{
  int year, month, day;
  const int year_weight = 100 * 100, month_weight = 100;
  sscanf(yytext, "%*c%d%*c%d%*c%d%*c", &year, &month, &day);
  if(check_date(year, month, day)){
    yylval -> number = year * year_weight + month * month_weight + day;
    RETURN_TOKEN(DATE);
  }
  yylval->string = strdup(yytext); RETURN_TOKEN(SSS);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 95 "lex_sql.l"
RETURN_TOKEN(SEMICOLON);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 96 "lex_sql.l"
RETURN_TOKEN(DOT);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 97 "lex_sql.l"
RETURN_TOKEN(EXIT);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 98 "lex_sql.l"
RETURN_TOKEN(HELP);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 99 "lex_sql.l"
RETURN_TOKEN(DESC);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "lex_sql.l"
RETURN_TOKEN(CREATE);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 101 "lex_sql.l"
RETURN_TOKEN(DROP);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 102 "lex_sql.l"
RETURN_TOKEN(TABLE);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 103 "lex_sql.l"
RETURN_TOKEN(TABLES);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 104 "lex_sql.l"
RETURN_TOKEN(UNIQUE);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 105 "lex_sql.l"
RETURN_TOKEN(INDEX);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 106 "lex_sql.l"
RETURN_TOKEN(ON);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 107 "lex_sql.l"
RETURN_TOKEN(SHOW);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 108 "lex_sql.l"
RETURN_TOKEN(SYNC);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 109 "lex_sql.l"
RETURN_TOKEN(SELECT);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 110 "lex_sql.l"
RETURN_TOKEN(CALC);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 111 "lex_sql.l"
RETURN_TOKEN(MAX_FUNC);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 112 "lex_sql.l"
RETURN_TOKEN(MIN_FUNC);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 113 "lex_sql.l"
RETURN_TOKEN(COUNT_FUNC);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 114 "lex_sql.l"
RETURN_TOKEN(AVG_FUNC);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 115 "lex_sql.l"
RETURN_TOKEN(SUM_FUNC);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 116 "lex_sql.l"
RETURN_TOKEN(LENGTH_FUNC);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 117 "lex_sql.l"
RETURN_TOKEN(DATE_FORMAT_FUNC);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 118 "lex_sql.l"
RETURN_TOKEN(ROUND_FUNC);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 119 "lex_sql.l"
RETURN_TOKEN(INNER);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 120 "lex_sql.l"
RETURN_TOKEN(JOIN);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 121 "lex_sql.l"
RETURN_TOKEN(FROM);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 122 "lex_sql.l"
RETURN_TOKEN(WHERE);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 123 "lex_sql.l"
RETURN_TOKEN(AS);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 124 "lex_sql.l"
RETURN_TOKEN(LK);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 125 "lex_sql.l"
RETURN_TOKEN(IS_OP);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 126 "lex_sql.l"
RETURN_TOKEN(IN_OP);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 127 "lex_sql.l"
RETURN_TOKEN(EXIST_OP);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 128 "lex_sql.l"
RETURN_TOKEN(NULL_VAL);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 129 "lex_sql.l"
RETURN_TOKEN(ORDER_BY);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 130 "lex_sql.l"
RETURN_TOKEN(GROUP_BY);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 131 "lex_sql.l"
RETURN_TOKEN(HAVING);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 132 "lex_sql.l"
RETURN_TOKEN(ASC);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 133 "lex_sql.l"
RETURN_TOKEN(AND);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 134 "lex_sql.l"
RETURN_TOKEN(OR);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 135 "lex_sql.l"
RETURN_TOKEN(NOT);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 136 "lex_sql.l"
RETURN_TOKEN(INSERT);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 137 "lex_sql.l"
RETURN_TOKEN(INTO);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 138 "lex_sql.l"
RETURN_TOKEN(VALUES);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 139 "lex_sql.l"
RETURN_TOKEN(DELETE);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 140 "lex_sql.l"
RETURN_TOKEN(UPDATE);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 141 "lex_sql.l"
RETURN_TOKEN(SET);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 142 "lex_sql.l"
RETURN_TOKEN(TRX_BEGIN);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 143 "lex_sql.l"
RETURN_TOKEN(TRX_COMMIT);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 144 "lex_sql.l"
RETURN_TOKEN(TRX_ROLLBACK);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 145 "lex_sql.l"
RETURN_TOKEN(INT_T);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 146 "lex_sql.l"
RETURN_TOKEN(STRING_T);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 147 "lex_sql.l"
RETURN_TOKEN(FLOAT_T);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 148 "lex_sql.l"
RETURN_TOKEN(DATE_T);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 149 "lex_sql.l"
RETURN_TOKEN(TEXT_T);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 150 "lex_sql.l"
RETURN_TOKEN(LOAD);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 151 "lex_sql.l"
RETURN_TOKEN(DATA);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 152 "lex_sql.l"
RETURN_TOKEN(INFILE);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 153 "lex_sql.l"
RETURN_TOKEN(EXPLAIN);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 154 "lex_sql.l"
yylval->string=strdup(yytext); RETURN_TOKEN(ID);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 155 "lex_sql.l"
RETURN_TOKEN(LBRACE);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 156 "lex_sql.l"
RETURN_TOKEN(RBRACE);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 158 "lex_sql.l"
RETURN_TOKEN(COMMA);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 159 "lex_sql.l"
RETURN_TOKEN(EQ);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 160 "lex_sql.l"
RETURN_TOKEN(LE);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 161 "lex_sql.l"
RETURN_TOKEN(NE);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 162 "lex_sql.l"
RETURN_TOKEN(NE);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 163 "lex_sql.l"
RETURN_TOKEN(LT);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 164 "lex_sql.l"
RETURN_TOKEN(GE);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 165 "lex_sql.l"
RETURN_TOKEN(GT);
	YY_BREAK
case 76:
#line 168 "lex_sql.l"
case 77:
#line 169 "lex_sql.l"
case 78:
#line 170 "lex_sql.l"
case 79:
YY_RULE_SETUP
#line 170 "lex_sql.l"
{ return yytext[0]; }
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 171 "lex_sql.l"
yylval->string = strdup(yytext); RETURN_TOKEN(SSS);
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 172 "lex_sql.l"
yylval->string = strdup(yytext); RETURN_TOKEN(SSS);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 174 "lex_sql.l"
LOG_DEBUG("Unknown character [%c]",yytext[0]); return yytext[0];
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 175 "lex_sql.l"
ECHO;
	YY_BREAK
#line 1856 "lex_sql.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 272 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 272 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 271);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 175 "lex_sql.l"


void scan_string(const char *str, yyscan_t scanner) {
  yy_switch_to_buffer(yy_scan_string(str, scanner), scanner);
}

bool check_date(int y, int m, int d)
{
    static int mon[] = {0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
    bool leap = (y % 400 == 0 || (y % 100 && y % 4 == 0));
    return (y > 0)
        && (m > 0)&&(m <= 12)
        && (d > 0)&&(d <= ((m==2 && leap)?1:0) + mon[m]);
}

